baseURL = "https://iriss04.github.io/02805_finalproject/"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "ananke"
publishDir = "docs"


DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
    background_color_class = "bg-dark-green"
    featured_image = "/images/greek.jpg"
    recent_posts_number = 10
    author = "Ana, Iris, Ruth"
    youtube = "https://www.youtube.com/watch?v=o2W3jfvZU4w&ab_channel=PascuyRodri"
    description = "The greatest network over Greek Mythology you will ever see, probably"